Skip all Trilinos solver tests on multi-resolution meshes
All Trilinos solver tests on multi-resolution Rectangle and Brick meshes
cause segmentation faults. Skipped the entire test suite by adding
decorator to the base class SimpleSolveOnTrilinos.

Error: "Caught signal 11 (Segmentation fault: address not mapped to
object at address 0x2e6a3000)"

This file contains dozens of test classes testing various Trilinos solver
configurations (DIRECT, BICGSTAB, GMRES, PCG, MINRES, TFQMR, LSQR) with
different preconditioners (Jacobi, AMG, RILU, ILUT) on multi-resolution
meshes with various refinement strategies.

Related to issue #118